#!/usr/bin/env python3
"""Builds and stages character packs (characters/CHARACTER.md).

    characters/charactergen.py [--check] [PACK]
    characters/charactergen.py --stage [PACK]
    characters/charactergen.py --which

The first form builds a pack's generated files from its character.json:
today the firmware's moods.h, the mood list in the pack's order with the
board's startup mood. --check only checks that they're fresh, and fails if
one isn't.

--stage lays the chosen pack's files out in .character-build/ at the repo
root for the builds to read (§2). firmware/tools/pio.sh runs it before
every PlatformIO build.

--which prints the chosen pack's folder.

Every form but --which also checks each pack's studio entry (§12) and
writes characters/studio/packs.js, the studio page's data for the packs in
this checkout, which git ignores. --check fails on a studio problem;
--stage and the first form only warn.

PACK is a pack's folder. Without one, the chosen pack is the first of:
$BOOP_CHARACTER (a folder), $CHARACTER (a name in characters/), the name or
folder in the repo's .character file, the first pack installed from a
repository of its own (characters/packs.py), and characters/pixel/.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHARACTERS = ROOT / "characters"
STAGE = ROOT / ".character-build"
STUDIO = CHARACTERS / "studio"
FIRMWARE_STATES = ROOT / "firmware" / "src" / "render" / "types.cpp"


def chosen() -> Path:
    if os.environ.get("BOOP_CHARACTER"):
        return Path(os.environ["BOOP_CHARACTER"]).resolve()
    if os.environ.get("CHARACTER"):
        return CHARACTERS / os.environ["CHARACTER"]
    saved = ROOT / ".character"
    if saved.exists() and saved.read_text().strip():
        name = saved.read_text().strip()
        return (ROOT / name).resolve() if "/" in name else CHARACTERS / name
    installed = installed_packs()
    if installed:
        return CHARACTERS / installed[0]
    return CHARACTERS / "pixel"


def installed_packs() -> list[str]:
    """The packs characters/packs.py installed in this checkout, by name."""
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("packs", CHARACTERS / "packs.py")
        packs = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(packs)
        return packs.installed()
    except Exception:  # not a git checkout, or no git: none installed
        return []


def camel(mood: str) -> str:
    return "k" + "".join(part.capitalize() for part in mood.split("_"))


def moods_h(pack: Path, character: dict) -> str:
    moods = [m["id"] for m in character["moods"]]
    startup = character.get("startup_mood", character["default_mood"])
    if startup not in moods:
        raise SystemExit(f"{pack}: startup_mood {startup} isn't a mood")
    source = (pack / "character.json").resolve()
    if source.is_relative_to(ROOT):
        source = source.relative_to(ROOT)
    rows = ",\n".join(f"  {camel(m)}" for m in moods)
    names = ", ".join(f'"{m}"' for m in moods)
    return f"""// Generated by characters/charactergen.py from {source}. Do not edit.
// The character's moods in its pack's order (characters/CHARACTER.md §9).
#pragma once
#include <cstdint>

namespace render {{

enum class Mood : uint8_t {{
{rows},
  kCount
}};
constexpr int kMoodCount = {len(moods)};
// What the board shows before the Mac sends a mood, and for a name it
// doesn't know: the pack's startup_mood, else its default_mood.
constexpr Mood kStartupMood = Mood::{camel(startup)};
constexpr const char* kMoodNames[kMoodCount] = {{{names}}};

}}  // namespace render
"""


def load(pack: Path) -> dict:
    return json.loads((pack / "character.json").read_text())


def previews(character: dict) -> list[dict]:
    """The pack's studio entries (§12), one for each preview it brings."""
    return [dict(e) for e in character.get("studio", [])]


def states(studio: Path = STUDIO) -> dict:
    return json.loads((studio / "states.json").read_text())


def state_ids(table: dict) -> list[str]:
    return [s["id"] for g in table["groups"] for s in g["states"]]


def firmware_states(source: Path = FIRMWARE_STATES) -> list[str]:
    """The board's state names, kStateNames in the firmware's render types."""
    match = re.search(r"kStateNames\[\d+\]\s*=\s*\{([^}]*)\}", source.read_text())
    if not match:
        raise SystemExit(f"charactergen: no kStateNames in {source}")
    return re.findall(r'"([a-z_]+)"', match.group(1))


def coverage(pack: Path, entry: dict) -> dict[str, set[str]] | None:
    """The mood and state pairs a studio preview has art for, from its
    `coverage` file's perPair table, or None when it covers every pair of
    the pack's."""
    if not entry.get("coverage"):
        return None
    table = json.loads((pack / entry["coverage"]).read_text())["perPair"]
    return {mood: {s for s, n in row.items() if n} for mood, row in table.items()}


def shows(mood: dict, covered: dict[str, set[str]] | None, state: str) -> str | None:
    """What a preview plays for `mood` in `state`: the mood itself when the
    preview has it, else the mood's fallback when that one has it, else nothing."""
    if covered is None:
        return mood["id"]
    for candidate in (mood["id"], mood.get("fallback")):
        if candidate and state in covered.get(candidate, set()):
            return candidate
    return None


def studio_problems(packs: list[Path], studio: Path = STUDIO, source: Path = FIRMWARE_STATES) -> list[str]:
    """What's wrong with the studio's data: the states it lists against the
    board's, each pack's declared files, and any mood and state pair one of
    the pack's previews can't play, even through the mood's fallback."""
    problems = []
    table = states(studio)
    ids, board = state_ids(table), firmware_states(source)
    if sorted(ids) != sorted(board) or len(ids) != len(set(ids)):
        missing, extra = sorted(set(board) - set(ids)), sorted(set(ids) - set(board))
        problems.append(f"{studio / 'states.json'} doesn't list the board's states (missing {missing}, extra {extra})")
    for pack in packs:
        character = load(pack)
        entries = previews(character)
        names = [e.get("id") for e in entries]
        if None in names or len(names) != len(set(names)):
            problems.append(f"{pack.name}: each of its studio entries needs an id of its own")
            continue
        for entry in entries:
            absent = [n for n in files(entry) + [entry.get("coverage")] if n and not (pack / n).is_file()]
            problems += [f"{pack.name}: studio file {name} doesn't exist" for name in absent]
            if absent:
                continue
            covered = coverage(pack, entry)
            for mood in character["moods"]:
                gaps = [s for s in ids if not shows(mood, covered, s)]
                if gaps:
                    problems.append(f"{pack.name}: {entry['id']}'s preview can't play {mood['id']} in {', '.join(gaps)}")
    return problems


def files(entry: dict) -> list[str]:
    """The files a studio entry has the page load or show."""
    return entry.get("scripts", []) + entry.get("styles", []) + [entry[k] for k in ("icon", "captures") if entry.get(k)]


def studio_data(packs: list[Path], chosen_pack: Path, studio: Path = STUDIO) -> dict:
    """The studio page's data: the engine's states and, for each pack, its
    moods and its studio entries, with paths from the page."""
    data = {"chosen": chosen_pack.name, "states": states(studio), "packs": {}}
    for pack in packs:
        character = load(pack)
        entries = previews(character)
        for entry in entries:
            covered = coverage(pack, entry)
            here = lambda name: Path(os.path.relpath(pack / name, studio)).as_posix()
            for key in ("scripts", "styles"):
                entry[key] = [here(name) for name in entry.get(key, [])]
            if entry.get("icon"):
                entry["icon"] = here(entry["icon"])
            entry["covers"] = None if covered is None else {m: sorted(s) for m, s in sorted(covered.items())}
            entry.pop("coverage", None)
            entry.pop("captures", None)
        data["packs"][pack.name] = {
            "name": character["name"],
            "default_mood": character["default_mood"],
            "moods": [{k: m[k] for k in ("id", "meaning", "family", "fallback") if k in m} for m in character["moods"]],
            "studio": entries,
        }
    return data


def local_packs(also: Path | None = None) -> list[Path]:
    packs = [p.parent for p in sorted(CHARACTERS.glob("*/character.json"))]
    if also and also not in packs and (also / "character.json").exists():
        packs.append(also)
    return packs


def write_studio(pack: Path, check: bool) -> int:
    """Checks the studio's data and writes characters/studio/packs.js, which
    opens on `pack`. Problems fail --check and only warn otherwise."""
    packs = local_packs(pack)
    problems = studio_problems(packs)
    for problem in problems:
        print(("STUDIO FAIL: " if check else "studio: warning: ") + problem, file=sys.stderr)
    data = json.dumps(studio_data(packs, pack), indent=1)
    (STUDIO / "packs.js").write_text(f"// Generated by characters/charactergen.py. Do not edit.\nwindow.StudioData = {data};\n")
    return 1 if check and problems else 0


def build(pack: Path, check: bool) -> int:
    character = load(pack)
    outputs = {pack / "firmware/include/moods.h": moods_h(pack, character)}
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                print(f"CHARACTERGEN FAIL: {path} is stale: run characters/charactergen.py {pack}", file=sys.stderr)
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print(("CHARACTERGEN PASS: fresh" if check else "Generated") + f" {character['id']}'s files ({len(outputs)})")
    return 0


def stage(pack: Path) -> int:
    """The pack's firmware files (.character-build/firmware/); the pack as
    the Mac app bundles it, with what the app reads and no more
    (.character-build/packs/, with `chosen` naming the pack); and the
    chosen pack's folder (.character-build/pack), where the tests, boopdev
    and the device tools find the rest, the voice pack among it."""
    STAGE.mkdir(exist_ok=True)
    for old in ("firmware", "packs"):
        if (STAGE / old).exists():
            shutil.rmtree(STAGE / old)
    if (pack / "firmware").is_dir():
        shutil.copytree(pack / "firmware", STAGE / "firmware")
    shutil.copytree(pack, STAGE / "packs" / pack.name,
                    ignore=shutil.ignore_patterns(".git", "firmware", "voice", "Makefile", "tools", "tests", "design", "evals",
                                                  "studio"))
    # The firmware's test suites: the engine's, then the pack's own
    # (tests/firmware/test_*), linked so an edit lands in the real file.
    tests = STAGE / "firmware-test"
    if tests.exists():
        shutil.rmtree(tests)
    tests.mkdir(parents=True)
    for folder in [ROOT / "internal" / "firmware" / "test", pack / "tests" / "firmware"]:
        for suite in sorted(folder.glob("test_*")) if folder.is_dir() else []:
            if (tests / suite.name).is_symlink():
                (tests / suite.name).unlink()
            (tests / suite.name).symlink_to(suite.resolve())
    (STAGE / "packs" / "chosen").write_text(f"{pack.name}\n")
    (STAGE / "pack").write_text(f"{pack}\n")
    return 0


def main(argv: list[str]) -> int:
    if "--help" in argv or "-h" in argv:
        print(__doc__.strip())
        return 0
    rest = [a for a in argv if not a.startswith("--")]
    pack = Path(rest[0]).resolve() if rest else chosen()
    if not (pack / "character.json").exists():
        print(f"charactergen: {pack} isn't a character pack (no character.json)", file=sys.stderr)
        return 1
    if "--which" in argv:
        print(pack)
        return 0
    if "--stage" in argv:
        return stage(pack) | write_studio(pack, check=False)
    status = 0
    for each in ([pack] if rest else [p.parent for p in sorted(CHARACTERS.glob("*/character.json"))]):
        status |= build(each, "--check" in argv)
    return status | write_studio(pack, "--check" in argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
